app/user/models.py
import datetime

from app.ext import db

"""
单项引用
双向引用
商品 ---》 主表      详情表 ---》 字表

一对一关系 
在商品中有详情的对象，在详情表中没有商品的对象 这种叫
"""


# 约束
# 主键约束  唯一约束  非空约束  默认约束
# 外键约束 关联关系

# 常用的数据类型
# 数字相关
# 字符串
# 日期时间
# 大文本  二进制数据

# 1000.00
# 100000

class User(db.Model):
    # __tablename__ = 't_user'
    uid = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True, nullable=True)
    weight = db.Column(db.Float(10, 2))
    # # decimal
    money = db.Column(db.Numeric(10, 2))
    create_date = db.Column(db.DateTime, default=datetime.datetime.now())
    # # 不要在text字段上面加索引
    msg = db.Column(db.Text())


#    外键

# 1>在主表建立外键连接的关系
# 2>在子表建立外键
class Cate(db.Model):
    cid = db.Column(db.Integer, primary_key=True)
    cname = db.Column(db.String(64), index=True, unique=True, nullable=True)
    # 建立关联关系的对象 懒加载
    """
    参数一 argument 关联的对象的类名
    参数二 lazy
            可选项：
            1·select 默认值 一条sql一条把所有相关的数据全部查出来
            2·dynamic 只查询主表的数据， 生成查询子表的sql 当我们需要使用字表的数据数据的时候再去查询
            3·immediate 等主表数据查询完成之后再去查询自标的数据
           
    back_populates 方向引用（当两个对象需要双向引用的时候使用） 值对应双向引用对象的字段 
    order_by=False  指定查询字表的排序字段
    uselist=None
    
    back-ref    backref='cate '    例如可以使用 shop.cate
    
    """
    shops = db.relationship('Shop', back_populates='cate', lazy='dynamic', uselist=True)


class Shop(db.Model):
    sid = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True, nullable=True)
    # 类名小写.关联字段
    cid = db.Column(db.Integer, db.ForeignKey(Cate.cid))
    cate = db.relationship('Cate', back_populates='shops')
    # 多对多肯定会有第三张表


# 角色 === 权限     增删该查的权限
# 管理员角色     增删改查的权限
# 普通用户      增查的权限
"""
参数  表的名称
"""
relation = db.Table('role_permission_relation',
                    db.Column('id', db.Integer, primary_key=True),
                    db.Column('per_id', db.Integer, db.ForeignKey('permission.per_id')),
                    db.Column('role_id', db.Integer, db.ForeignKey('role.role_id'))
                    )


# secondary 用于多对多， 指向第三张表
class Role(db.Model):
    role_id = db.Column(db.Integer, primary_key=True)
    role_name = db.Column(db.String(64), nullable=False, index=True, unique=True)
    desc = db.Column(db.Text)
    permissions = db.relationship('Permission', secondary=relation)

    def __init__(self, role_name, desc):
        self.role_name = role_name
        self.desc = desc


# 权限
class Permission(db.Model):
    per_id = db.Column(db.Integer, primary_key=True)
    per_name = db.Column(db.String(64), nullable=False, index=True, unique=True)
    desc = db.Column(db.Text)

    def __init__(self, per_name, desc):
        self.per_name = per_name
        self.desc = desc

app/user/__init__.py
from flask import Blueprint

users = Blueprint('user', __name__, template_folder='templates')
import app.user.views

app/user/views.py
from flask import render_template, request, redirect, url_for

from app.ext import db
from app.user import users
from .models import User, Shop, Cate, Role, Permission


@users.route('/show/')
def show():
    # 过滤列
    query = db.session.query(User.name).all()
    users = User.query.all()
    user = User.query.filter_by(name='test1').first()
    return '查询'


@users.route('/save/')
def save_all():
    objects = []
    for i in range(1, 101):
        objects.append(User(name='name' + str(i), weight='10' + str(i), money='3485' + str(i), msg='message' + str(i)))
    db.session.bulk_save_objects(objects)
    db.session.commit()
    return '批量保存'


@users.route('/limit/')
# @users.route('/limit/<int:page>/<int:size>/')
# def query_limit(page, size):
def query_limit():
    page = request.values.get('page', default=1, type=int)
    size = request.values.get('size', default=10, type=int)
    paginate = User.query.order_by(User.uid).paginate(page=page, per_page=size, error_out=False)
    users = paginate.items
    print(users)
    print(paginate.total)
    print(paginate.pages)
    print(paginate.page)
    print(paginate.has_prev)
    print(paginate.has_next)
    # print(user.query_limit)
    return render_template('user/users.html', users=users, paginate=paginate)


@users.route('/insert/', methods=['get', 'post'])
def add():
    if request.method == 'GET':
        return render_template('zsgc/add.html')
    elif request.method == 'POST':
        name = request.values.get('name')
        weight = request.values.get('weight')
        money = request.values.get('money')
        message = request.values.get('msg')
        user = User(name=name, weight=float(weight), money=money, msg=message)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.query_limit'))


@users.route('/update/', methods=['get', 'post'])
def update():
    if request.method == 'GET':
        uid = request.values.get('uid', type=int)
        user = User.query.get(uid)
        return render_template('zsgc/update.html', user=user)
    elif request.method == 'POST':
        uid = request.values.get('uid', type=int)
        name = request.values.get('name', type=str)
        weight = request.values.get('weight', type=float)
        money = request.values.get('money')
        create_date = request.values.get('create_date')
        msg = request.values.get('msg')
        User.query.filter(User.uid == uid).update(
            {User.name: name, User.weight: weight, User.money: money, User.create_date: create_date, User.msg: msg})
        db.session.commit()
        return redirect('/user/limit/')


# 分类菜单
@users.route('/1/')
def test():
    # 通过一的一方查询多的一方
    cates = Cate.query.all()
    for cate in cates:
        # shops = Shop.query.filter(Shop.cid == cate.cid).all()
        print(cate.cname)
        print(cate.shops[0].name)
    # 通过多的一方查询一的一方
    shop = Shop.query.first()
    print(shop.cate.cname)
    Cate.query.filter(Cate.cid == shop.cid)


# ==========多对多=============
@users.route('/add/role/')
def add_role():
    role = Role('admin', '超级管理员')
    db.session.add(role)
    db.session.add_all([Permission('insert', '添加操作'),
                        Permission('delete', '删除操作'),
                        Permission('update', '更新操作'),
                        Permission('select', '查看操作')])
    db.session.commit()
    return '添加权限角色'


@users.route('/add/role/per/')
def add_role_per():
    admin = Role.query.get(1)
    admin.permissions = Permission.query.all()
    db.session.commit()
    return '添加权限角色'


@users.route('/find/role/')
def find_role():
    role = Role.query.get(1)
    for per in role.permissions:
        print(per.per_name)
    return '通过角色查询对象'


@users.route('/del/msg/')
def del_msg():
    if has_per():
        return '删除成功'
    else:
        return '没有相关数据，请与管理员联系'


def has_per():
    role = Role.query.get(1)
    for per in role.permissions:
        if per.per_name == 'delete':
            return True
    return False


@users.route('/del/per/')
def del_per(per):
    return

app/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello</h1>
</body>
</html>

app/templates/user/users.html
<!DOCTYPE html>
{% import 'macro/macro.html' as macro %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        table {
            width: 100%;
            border-collapse: collapse;
        }

        td, th {
            border: 1px solid blue;
            text-align: center;
        }

        ul {
            list-style: none;
            margin: 0px;
            padding: 0px;
        }

        ul li {
            float: left;
        }

        ul a {
            text-decoration: none;
            font-size: 15px;
            cursor: pointer;
            color: black;
        }
    </style>

</head>
<body>
<table>
    <tr>
        <th>ID</th>
        <th>用户名</th>
        <th>体重</th>
        <th>资金</th>
        <th>注册时间</th>
        <th>详细信息</th>
        <th>操作</th>
    </tr>
    {% for user in users %}
        <tr>
            <td>{{ user.uid }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.weight }}</td>
            <td>{{ user.money }}</td>
            <td>{{ user.create_date }}</td>
            <td>{{ user.msg }}</td>
            <td>
                <a href="{{ url_for('user.add') }}">添加</a>
                <a href="{{ url_for('user.update') }}?uid={{ user.uid }}">修改</a>
                <a href="#">删除</a>
            </td>
        </tr>
    {% endfor %}
</table>

{% if paginate %}
    <div>
        {#
        1·'user.query_limit' user是蓝图Blueprint的第一个参数name
        2·query_limit 是views中定义的函数，通常和url_for连用，动态返回url
#}
        {{ macro.input(paginate,'user.query_limit') }}
    </div>
{% endif %}
</body>
</html>